//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pw.Elka.Bd2.Tests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient_Poufne
    {
        public int id_klient { get; set; }
        public long pesel { get; set; }
        public string adres { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
