//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pw.Elka.Bd2.Tests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozycja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pozycja()
        {
            this.Rewers = new HashSet<Rewers>();
            this.Rezerwacja = new HashSet<Rezerwacja>();
            this.Autor = new HashSet<Autor>();
            this.Gatunek = new HashSet<Gatunek>();
        }
    
        public int id_pozycja { get; set; }
        public Nullable<long> isbn { get; set; }
        public string nazwa { get; set; }
        public short rok { get; set; }
        public byte[] zdjecie { get; set; }
        public Nullable<System.DateTime> dostepna_od { get; set; }
        public bool wypozyczona { get; set; }
        public short id_dzial { get; set; }
        public Nullable<int> id_seria { get; set; }
        public short id_typ { get; set; }
    
        public virtual Dzial Dzial { get; set; }
        public virtual Seria Seria { get; set; }
        public virtual Typ Typ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rewers> Rewers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autor> Autor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gatunek> Gatunek { get; set; }
    }
}
